name: Build Project on Multiple OS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Poetry
        run: |
          python -m pip install poetry
          python -m poetry --version
        shell: bash
      
      - name: Verify Poetry Installation
        run: |
          which poetry
          python -c "import sys; print(sys.executable)"
        shell: bash
      
      - name: Configure Poetry
        run: |
          python -m poetry config virtualenvs.create true
          python -m poetry config virtualenvs.in-project true
        shell: bash
      
      - name: Install dependencies
        run: |
          python -m poetry install --no-interaction --no-root
        shell: bash
      
      - name: Build the project
        run: |
          python -m poetry build
        shell: bash
      
      - name: Run tests
        run: |
          python -m poetry run pytest
        shell: bash
