name: Build Project on Multiple OS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Poetry
        run: |
          pipx install poetry
          poetry --version
      
      - name: Add Poetry to PATH
        run: |
          poetry env use python3.11
          poetry env info
      
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      
      - name: Build the project
        run: poetry build
      
      - name: Run tests
        run: poetry run pytest
