name: Build Project on Multiple OS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
      
      - name: Install dependencies
        run: |
          $PYTHON_COMMAND -m poetry install --no-interaction --no-root
        shell: bash
        env:
          PYTHON_COMMAND: python
      
      - name: Build the project
        run: |
          $PYTHON_COMMAND -m poetry build
        shell: bash
        env:
          PYTHON_COMMAND: python
      
      - name: Run tests
        run: |
          $PYTHON_COMMAND -m poetry run pytest
        shell: bash
        env:
          PYTHON_COMMAND: python
