name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install Project Dependencies
      run: |
        poetry install

  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    needs: install_dependencies  # Zależy od "install_dependencies"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies for Linter and Security
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit black
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Security check with bandit
      run: bandit -r .

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: install_dependencies  # Zależy od "install_dependencies"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Project Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run Unit Tests with pytest
      run: pytest
