name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install Project Dependencies
      run: |
        poetry install

  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    needs: install_dependencies  # Zależy od "install_dependencies"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies for Linter and Security
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install  # Instalacja zależności za pomocą Poetry
    - name: Run Linter (Lint)
      run: poetry run task lint  # Uruchomienie lintera zdefiniowanego w Poetry
    - name: Run Formatter
      run: poetry run task formatter  # Uruchomienie formatera kodu
    - name: Run Security Checks
      run: poetry run task security  # Uruchomienie analizy bezpieczeństwa

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: install_dependencies  # Zależy od "install_dependencies"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Project Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install  # Instalacja zależności za pomocą Poetry
    - name: Run Unit Tests with pytest
      run: poetry run task test  # Uruchomienie testów zdefiniowanych w Poetry
